str_1 = input("Write your string: ")
str_1 = str_1.replace("a", "").replace("A", "")
str_1 = str_1.replace("e", "").replace("E", "")
str_1 = str_1.replace("i", "").replace("I", "")
str_1 = str_1.replace("o", "").replace("O", "")
str_1 = str_1.replace("u", "").replace("U", "")
print(str_1)