a = int(input("Write a: "))
b = int(input("Write b: "))
print(f"sum: {a + b}")
print(f"difference: {a - b}")
print(f"composition: {a * b}")
print(f"the quotient of division: {a // b}")
print(f"the remainder of the division: {a % b}")
print(f"exponentiation: {a ** b}")